openapi: 3.0.0
info:
  title: Libraries
  description: API documentation of libraries
  version: 1.0.0
paths:
  /region:
    get:
      tags:
      - Region
      description: Vrací všechny kraje
      summary: Vrací všechny kraje
      operationId: getRegions
      responses:
        "200":
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/region'
          description: Vrátí všechny kraje
        "401":
          description: Nemá práva
  /region/{regionID}/library:
    get:
      tags:
      - Region
      description: Vrátí všechny knihovny v konkrétním kraji
      summary: Vrátí všechny knihovny v konkrétním kraji
      operationId: getLibrariesInRegion
      parameters:
      - name: regionID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/library'
          description: Vrátí všechny knihovny v daném kraji
        "401":
          description: Nemá práva
        "404":
          description: Kraj neexistuje
  /library:
    get:
      tags:
      - Library
      description: Vrátí všechny knihovny
      summary: Vrátí všechny knihovny
      operationId: getLibraries
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/library'
          description: Vrátí všechny knihovny
        "401":
          description: Nemá práva
    post:
      tags:
      - Library
      description: Vytvoří knihovnu a vrátí ji
      summary: Vytvoří knihovnu a vrátí ji
      operationId: postLibrary
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/library'
      responses:
        "201":
          description: Vytvoří novou knihovnu a vrátí ji
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/region'
        "400":
          description: Špatná data
        "409":
          description: Knihovna už existuje
        "401":
          description: Nemá práva
  /library/{libraryID}:
    delete:
      tags:
      - Library
      description: Odstraní knihovnu, nevrátí nic
      summary: Odstraní knihovnu, nevrátí nic
      operationId: deleteLibrary
      parameters:
      - name: libraryID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: "Odstraní knihovnu, ale nevrátí nic"
        "401":
          description: Nemá práva
        "404":
          description: Knihovna neexistuje
  /library/{libraryID}/genre:
    get:
      tags:
      - Library
      description: Vrátí všechny žánry v dané knihovně
      summary: Vrátí všechny žánry v dané knihovně
      operationId: getGenresInLibrary
      parameters:
      - name: libraryID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/genre'
          description: Vrátí všechny žánry v dané knihovně
        "401":
          description: Nemá práva
        "404":
          description: Knihovna neexistuje
    post:
      tags:
      - Library
      description: Vytvoří nový žánr v dané knihovně
      summary: Vytvoří nový žánr v dané knihovně
      operationId: postGenresInLibrary
      parameters:
      - name: libraryID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/genre'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genre'
          description: Vytvoří nový žánr v dané knihovně a následně ho vrátí
        "400":
          description: Špatná data
        "401":
          description: Nemá práva
        "409":
          description: Žánr v dané knihovně už existuje
  /library/{libraryID}/genre/{genreID}:
    delete:
      tags:
      - Library
      description: Smaže žánr v dané knihovně
      summary: Smaže žánr v dané knihovně
      operationId: deleteGenreInLibrary
      parameters:
      - name: libraryID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: genreID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: Odstraní žánr v dané knihovně, ale nevrátí nic
        "401":
          description: Nemá práva
        "404":
          description: Žánr v dané knihovně neexistuje
  /library/{libraryID}/author:
    get:
      tags:
      - Library
      description: Vrátí všechny autory/ky nalezitelné v dané knihovně
      summary: Vrátí všechny autory/ky nalezitelné v dané knihovně
      operationId: getAuthorsInLibrary
      parameters:
      - name: libraryID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/author'
          description: Vrátí všechny autory/ky v dané knihovně
        "401":
          description: Nemá práva
        "404":
          description: Knihovna neexistuje
    post:
      tags:
      - Library
      description: Vytvoří nového autora v dané knihovně
      summary: Vytvoří nového autora v dané knihovně
      operationId: postAuthorsInLibrary
      parameters:
      - name: libraryID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/author'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/author'
          description: Vytvoří nového autora v dané knihovně a následně ho vrátí
        "400":
          description: Špatná data
        "401":
          description: Nemá práva
        "409":
          description: Autor v dané knihovně už existuje
  /library/{libraryID}/author/{authorID}:
    delete:
      tags:
      - Library
      description: Smaže autora v dané knihovně
      summary: Smaže autora v dané knihovně
      operationId: deleteAuthorInLibrary
      parameters:
      - name: libraryID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: authorID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: Odstraní autora v dané knihovně, ale nevrátí nic
        "401":
          description: Nemá práva
        "404":
          description: Autor v dané knihovně neexistuje
  /genre:
    get:
      tags:
      - Genre
      description: Vrátí všechny žánry
      summary: Vrátí všechny žánry
      operationId: getGenres
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/genre'
          description: Vrátí všechny žánry
        "401":
          description: Nemá práva
    post:
      tags:
      - Genre
      description: Vytvoří nový žánr
      summary: Vytvoří nový žánr
      operationId: postGenre
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/genre'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genre'
          description: Vytvoří nový žánr a následně ho vrátí
        "400":
          description: Špatná data
        "401":
          description: Nemá práva
        "409":
          description: Žánr už existuje
  /genre/{genreID}:
    delete:
      tags:
      - Genre
      description: Smaže žánr
      summary: Smaže žánr
      operationId: deleteGenre
      parameters:
      - name: genreID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: Odstraní žánr, ale nevrátí nic
        "401":
          description: Nemá práva
        "404":
          description: Žánr neexistuje
  /genre/{genreID}/book:
    get:
      tags:
      - Genre
      description: Vrátí všechny knihy v daném žánru
      summary: Vrátí všechny knihy v daném žánru
      operationId: getBooksInGenre
      parameters:
      - name: genreID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/book'
          description: Vrátí všechny knihy v daném žánru
        "401":
          description: Nemá práva
        "404":
          description: Žánr neexistuje
  /author:
    get:
      tags:
      - Author
      description: Vrátí všechny autory/ky
      summary: Vrátí všechny autory/ky
      operationId: getAuthors
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/author'
          description: Vrátí všechny autory/ky
        "401":
          description: Nemá práva
    post:
      tags:
      - Author
      description: Vytvoří nového autora/ku
      summary: Vytvoří nového autora/ku
      operationId: postAuthor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/author'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/author'
          description: Vytvoří nového autora/ku a následně ho/ji vrátí
        "400":
          description: Špatná data
        "401":
          description: Nemá práva
        "409":
          description: Autor/ka už existuje
  /author/{authorID}:
    delete:
      tags:
      - Author
      description: Smaže autora
      summary: Smaže autora
      operationId: deleteAuthor
      parameters:
      - name: authorID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: Odstraní autora/ku, nevrátí nic
        "401":
          description: Nemá práva
        "404":
          description: Autor/ka neexistuje
  /author/{authorID}/book:
    get:
      tags:
      - Author
      description: Vrátí všechny knihy se specifickým autorem
      summary: Vrátí všechny knihy se specifickým autorem
      operationId: getBooksFromAuthor
      parameters:
      - name: authorID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/book'
          description: Vrátí všechny knihy od daného autora
        "401":
          description: Nemá práva
        "404":
          description: Autor/ka neexistuje
  /book:
    get:
      tags:
      - Book
      description: Vrátí všechny knihy
      summary: Vrátí všechny knihy
      operationId: getBooks
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/book'
          description: Vrátí všechny knihy
        "401":
          description: Nemá práva
    post:
      tags:
      - Book
      description: Vytvoří knihu a vrátí ji
      summary: Vytvoří knihu a vrátí ji
      operationId: postBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Vytvoří novou knihu a následně ji vrátí
        "400":
          description: Špatná data
        "401":
          description: Nemá práva
        "409":
          description: Kniha už existuje
  /book/{bookID}:
    delete:
      tags:
      - Book
      description: Odstraní knihu, nevrátí nic
      summary: Odstraní knihu, nevrátí nic
      operationId: deleteBook
      parameters:
      - name: bookID
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: Odstraní knihu, nevrátí nic
        "401":
          description: Nemá práva
        "404":
          description: Kniha neexistuje
components:
  schemas:
    region: 
      description: Část státu, ve které se nachází jednotlivé knihovny
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          example: 10
        name:
            type: string
            example: Pardubický
        libraries:
          type: array
          items:
            properties:
              id:
                type: integer
                format: int64
                example: 5
              name:
                type: string
                example: Městská knihovna v Praze
    library:
      description: Nachází se v kraji, je rozdělena na žánry
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          example: 5
        name:
          type: string
          example: Městská knihovna v Praze
        adress:
          type: string
          example: Wassermannova 926/16, Praha 5
        region:
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 10
            name:
                type: string
                example: Pardubický
        genres:
          type: array
          items:
            properties:
              id:
                type: integer
                format: int64
                example: 4
              name:
                type: string
                example: Fantasy
        authors:
          type: array
          items:
            properties:
              id:
                type: integer
                format: int64
                readOnly: true
                example: 3
              name:
                type: string
                example: Beton Betonový
        books:
          type: array
          items:
            properties:
              id:
                type: integer
                format: int64
                example: 31
              name:
                type: string
                example: Harry Potter a Kámen mudrců
    genre:
      description: Určitá část knihovny. Obsahuje jednotlivé knihy
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          example: 4
        name:
          type: string
          example: Fantasy
        books:
          type: array
          items:
            properties:
              id:
                type: integer
                format: int64
                example: 31
              name:
                type: string
                example: Harry Potter a Kámen mudrců
    author:
      description: Člověk, který napsal knihu
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          example: 3
        name:
          type: string
          example: Beton Betonový
        books:
          type: array
          items:
            properties:
              id:
                type: integer
                format: int64
                example: 31
              name:
                type: string
                example: Harry Potter a Kámen mudrců
    book:
      description: Má svého autora/y/ku/ky a patří do určitého žánru
      type: object
      properties:
        ISBN:
          type: string
          example: 978-80-00-06758-2
        name:
          type: string
          example: Harry Potter a Kámen mudrců
        issueNumber:
          type: integer
          format: int64
          example: 2
        authors:
          type: array
          items:
            properties:
              id:
                type: integer
                format: int64
                example: 3
              name:
                type: string
                example: Beton Betonový
        genres:
          type: array
          items:
            properties:
              id:
                type: integer
                format: int64
                example: 4
              name:
                type: string
                example: Fantasy
        pages:
          type: integer
          format: int64
          example: 420
        content:
          type: string
          example: Až do svých jedenáctých narozenin si o sobě Harry myslel, že je jen obyčejný chlapec. Pak ale dostal soví poštou dopis, kterým byl zván ke studiu na prestižní soukromé Škole čar a kouzel v Bradavicích, a jeho život se rázem proměnil. Leccos se dozvídá o minulosti svých zemřelých rodičů, získá pár dobrých kamarádů, naučí se mistrovsky hrát famfrpál a kvůli Kameni mudrců podstoupí smrtelný souboj se zloduchem Voldemortem...
        year:
         type: integer
         format: int64
         example: 2001
        language:
          type: string
          example: czech